#!/bin/bash
# Usage: A bash script intended to be used instead of scriptcs on Linux.
# Author: François NOUAILLE-DEGORCE
# -------------------------------------------------
 
# Create a temporary file which will be the compilation result of our file. 
tmp=$(mktemp)
# Make the compilation. You can use Microsoft's csc as well.
# Here we add a refezrence to System.Windows.Forms.dll in a dirty way.
# We should check first if we need it!
mcs ${1} -out:${tmp} -r:System.Windows.Forms.dll
# Remove the temporary file one second later.
# So if the program is not ending correctly,
# the temporary file is gonna be deleted anyway.
sleep 1 && rm ${tmp} &
# Run the file with mono.
mono ${tmp}